### PR TITLE
Miscellaneous Changes

### PR DESCRIPTION
**Pull request by Tauwasser**
Two changes, one for badges and one for boulder dust gfx.

Although not committed yet, the badges bytes are checked when performing FLY, STRENGTH etc. through the Pokémon menu.

### CODE REVIEW

**Comment by Tauwasser** [comment]
added labels to code that loads emotes, jump shadow but also some people graphics

**Comment by mid-kid** [comment]
Wram labels should be prefixed with `w`. Also, are you sure `KantoBadges` and `JohtoBadges` are appropriate names? Why not make `wBadges` a `dw`?

**Comment by Tauwasser** [comment]
Sometimes only Kanto or Johto are used and it serves to identify which is which. I could revamp it to what pokecrystal does and use wBadges in addition to the other labels.

**Comment by Tauwasser** [comment]
I'll improve this PR and create a 2nd PR.

**Pull request closed without merging**
