### PR TITLE
More rom0 dism

### PR DESCRIPTION
**Pull request by PikalaxALT**

### CODE REVIEW

**Comment by PikalaxALT** [comment]
Please merge this within the next 24 hours.  After that time expires, I will close this request.  I have left the discord server already.  Do not attempt to contact me through Discord.

**Comment by Sanqui** [comment]
I'm not sure what happened here, but if there was a conflict, please bring it up with me as I would like to mediate.

**Comment by PikalaxALT** [comment]
Closing this request and deleting my fork. Good bye.

**Comment by theclashingfritz** [comment]
What in the world... I don't star and watch repo's to see a damn salt train. Jesus.

**Pull request closed without merging**
