### PR TITLE
Fill in named constants & values for moves

### PR DESCRIPTION
**Pull request by jd-0**
How does one "percent" Rollout's accuracy value of 78.5?

### CODE REVIEW

**Comment by ketsuban** [comment]
Get as close as you can with `{integer} percent`, then add/subtract a small quantity to get the exact value. There's plenty of cases of `percent + 1` and `percent - 1` in `pokecrystal`.

**Comment by Rangi42** [comment]
Some common `percent` values: https://github.com/pret/pokecrystal/blob/master/macros/data.asm#L3

**Comment by jd-0** [comment]
So, is this okay? Or is there a better way:
I edited the "move" macro to allow for "percent - \8" as needed.
Sorry, I'm a noob! haha.

**Comment by Rangi42** [comment]
@jd-0 Since not all the values can be represented as clean percentages, unlike the final, I would just make the macro a simple `db \5` and repeat `percent` for all 251 moves.

**Comment by jd-0** [comment]
I think I got it now, thanks for clarifying!

**Comment by Rangi42** [comment]
Thank you! One more thing: please align the number columns so that the one's place is lined up; note how pokegold/pokecrystal do it.

**Comment by jd-0** [comment]
There we go, much nicer!

**Pull request merged**
