### PR TITLE
Added installation notes

### PR DESCRIPTION
**Pull request by ojdon**
I made some notes on the initial project setup, especially for MacOS users.

### CODE REVIEW

**Comment by ISSOtm** [comment]
What prevents `make` to be used on MacOS?

**Comment by ketsuban** [comment]
The Homebrew recipe for GNU `make` installs it as `gmake` to avoid colliding with an official (BSD) `make`. There's [a folder you can add](https://formulae.brew.sh/formula/make) to `PATH` to make it available as `make`.

**Comment by mid-kid** [comment]
@ketsuban Mac OSX uses GNU Make 3.81 by default, but this makefile is incompatible with that for some reason that isn't inmediately obvious to me.

**Comment by Rangi42** [comment]
The README has since been revised. INSTALL.md may be adapted from pokegold/pokecrystal later.

**Pull request closed without merging**
